gallery/urls.py
from django.urls import path

from gallery.views import ImageView, ImageList, AlbumView, AlbumList, ImageCreate

app_name = 'gallery'
urlpatterns = [
    path('', AlbumList.as_view(), name='album_list'),
    path('images/', ImageList.as_view(), name='image_list'),
    path('image/<int:pk>/<slug>', ImageView.as_view(), name='image_detail'),
    path('upload/', ImageCreate.as_view(), name='image_upload'),
    path('album/<int:pk>/<slug>/', AlbumView.as_view(), name='album_detail'),
    path('album/<int:apk>/<int:pk>/<slug>', ImageView.as_view(), name='album_image_detail')
]

gallery/templates/gallery/partials/image_upload_form.html
{% if form.errors %}
    <div class="alert alert-warning">
        {{ form.errors }}
    </div>
{% endif %}

{% if messages %}
    <div class="alert alert-info">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %}

<form method="post" id="image_upload_form"
      action="{% url 'gallery:image_upload' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <input id="data" type="file" name="data" data-url="{% url 'gallery:image_upload' %}" multiple>

    <!--
    <div id="progress">
        <div class="progressbar"></div>
    </div>-->
    <input type="submit"/>

    <input type="hidden" name="apk" value="{{ album.pk }}"/>
    <input type="hidden" name="next" value="{{ request.path }}"/>

</form>

gallery/templates/gallery/partials/justify_images.html
{% load static %}
<script>
    /** Use values from app settings */
    hdpi_factor = {{ hdpi_factor }};
    image_margin = {{ image_margin }};
</script>
<script type="text/javascript" src="{% static 'gallery/js/justify_images.js' %}"></script>

gallery/templates/gallery/partials/thumbnail.html
<div class="thumbnail">

        <img id="image_empty_{{ image.pk }}"
             class="image image_spacer"
             alt="{{ image.title }}"
             data-src="{{ image.data_thumbnail.url }}"
             style="width: {% widthratio image.data_thumbnail.width 2 1 %}px"/>

        <div class="overlay image_spacer">

            <div class="label"> {{ image.title }} </div>

        </div>

</div>

gallery/templates/gallery/partials/thumbnail_empty.html
{% load static %}

<div class="thumbnail">

        <img id="image_{{ forloop.counter0 }}"
             class="image empty"
             alt="{{ album.title }}"
             data-src="{% static 'gallery/images/album.png' %}"
             style="margin-right: {{ image_margin }}px"/>

        <div class="overlay image_spacer">

            <div class="label"> {{ album.title }} </div>

        </div>

</div>

gallery/templates/gallery/partials/thumbnail_preview.html
<div class="thumbnail" style="display: block">

    <img id="image_{{ image.pk }}"
         class="image"
         alt="{{ image.title }}"
         src="{{ image.data_thumbnail.url }}">

    <div class="overlay">

        <div class="label preview"> {{ image.title }} </div>

    </div>

</div>